
export type Course = {
    code: string;
    name: string;
    unswUrl: string;
    year: number;
    term: number;

    mark?: number;
    grade?: string;
    currentlyTaking?: boolean;

    description: string;
};

export const courses: Course[] = [
    {
        year: 2024,
        term: 1,
        code: "COMP1511",
        name: "Programming Fundamentals",
        unswUrl: "https://www.handbook.unsw.edu.au/undergraduate/courses/current/COMP1511",
        mark: 89,
        grade: "HD",
        description: "",
    },
    {
        year: 2024,
        term: 1,
        code: "MATH1131",
        name: "Mathematics 1A",
        unswUrl: "https://www.handbook.unsw.edu.au/undergraduate/courses/current/MATH1131",
        mark: 81,
        grade: "DN",
        description: "",
    },
    {
        year: 2024,
        term: 1,
        code: "PHYS1121",
        name: "Physics 1A",
        unswUrl: "https://www.handbook.unsw.edu.au/undergraduate/courses/current/PHYS1121",
        grade: "SY",
        description: "",
    },

    {
        year: 2024,
        term: 2,
        code: "MATH1231",
        name: "Mathematics 1B",
        unswUrl: "https://www.handbook.unsw.edu.au/undergraduate/courses/current/MATH1231",
        mark: 85,
        grade: "HD",
        description: "",
    },
    {
        year: 2024,
        term: 2,
        code: "ENGG1300",
        name: "Engineering Mechanics",
        unswUrl: "https://www.handbook.unsw.edu.au/undergraduate/courses/current/ENGG1300",
        mark: 80,
        grade: "DN",
        description: "",
    },
    {
        year: 2024,
        term: 2,
        code: "COMP1531",
        name: "Software Engineering Fundamentals",
        unswUrl: "https://www.handbook.unsw.edu.au/undergraduate/courses/current/COMP1531",
        mark: 100,
        grade: "HD",
        description: "",
    },

    {
        year: 2024,
        term: 3,
        code: "DESN1000",
        name: "Engineering Design",
        unswUrl: "https://www.handbook.unsw.edu.au/undergraduate/courses/current/DESN1000",
        mark: 83,
        grade: "DN",
        description: "",
    },
    {
        year: 2024,
        term: 3,
        code: "ELEC1111",
        name: "Electrical Circuit Fundamentals",
        unswUrl: "https://www.handbook.unsw.edu.au/undergraduate/courses/current/ELEC1111",
        mark: 91,
        grade: "HD",
        description: "",
    },
    {
        year: 2024,
        term: 3,
        code: "COMP1521",
        name: "Computer Systems Fundamentals",
        unswUrl: "https://www.handbook.unsw.edu.au/undergraduate/courses/current/COMP1521",
        mark: 94,
        grade: "HD",
        description: "",
    },

    {
        year: 2025,
        term: 1,
        code: "MATH2018",
        name: "Engineering Mathematics 2D",
        unswUrl: "https://www.handbook.unsw.edu.au/undergraduate/courses/current/MATH2018",
        mark: 89,
        grade: "HD",
        description: "",
    },
    {
        year: 2025,
        term: 1,
        code: "ELEC2141",
        name: "Digital Circuit Design",
        unswUrl: "https://www.handbook.unsw.edu.au/undergraduate/courses/current/ELEC2141",
        mark: 94,
        grade: "HD",
        description: "",
    },
    {
        year: 2025,
        term: 1,
        code: "COMP2521",
        name: "Data Structures and Algorithms",
        unswUrl: "https://www.handbook.unsw.edu.au/undergraduate/courses/current/COMP2521",
        mark: 97,
        grade: "HD",
        description: "",
    },

    {
        year: 2025,
        term: 2,
        code: "COMP2511",
        name: "Object-Oriented Design & Programming",
        unswUrl: "https://www.handbook.unsw.edu.au/undergraduate/courses/current/COMP2511",
        mark: 90,
        grade: "HD",
        description: "",
    },
    {
        year: 2025,
        term: 2,
        code: "COMP6841",
        name: "Extended Security Engineering and Cyber Security",
        unswUrl: "https://www.handbook.unsw.edu.au/undergraduate/courses/current/COMP6841",
        mark: 83,
        grade: "DN",
        description: "",
    },
    {
        year: 2025,
        term: 2,
        code: "MMAN2300",
        name: "Engineering Mechanics 2",
        unswUrl: "https://www.handbook.unsw.edu.au/undergraduate/courses/current/MMAN2300",
        mark: 88,
        grade: "HD",
        description: "",
    },

    {
        year: 2025,
        term: 3,
        code: "MATH2089",
        name: "Numerical Methods and Statistics",
        unswUrl: "https://www.handbook.unsw.edu.au/undergraduate/courses/current/MATH2089",
        mark: 89,
        grade: "HD",
        description: "",
    },
    {
        year: 2025,
        term: 3,
        code: "MTRN2500",
        name: "Computing for Mechatronic Engineers",
        unswUrl: "https://www.handbook.unsw.edu.au/undergraduate/courses/current/MTRN2500",
        mark: 96,
        grade: "HD",
        description: "",
    },
    {
        year: 2025,
        term: 3,
        code: "MMAN1130",
        name: "Design and Manufacturing",
        unswUrl: "https://www.handbook.unsw.edu.au/undergraduate/courses/current/MMAN1130",
        mark: 87,
        grade: "HD",
        description: "",
    },

    {
        year: 2026,
        term: 1,
        currentlyTaking: true,
        code: "COMP6443",
        name: "Web Application Security and Testing",
        unswUrl: "https://www.handbook.unsw.edu.au/undergraduate/courses/current/COMP6443",
        description: "",
    },
    {
        year: 2026,
        term: 1,
        currentlyTaking: true,
        code: "ENGG2400",
        name: "Mechanics of Solids 1",
        unswUrl: "https://www.handbook.unsw.edu.au/undergraduate/courses/current/ENGG2400",
        description: "",
    },
    {
        year: 2026,
        term: 1,
        currentlyTaking: true,
        code: "MMAN3210",
        name: "Feedback Control Systems",
        unswUrl: "https://www.handbook.unsw.edu.au/undergraduate/courses/current/MMAN3210",
        description: "",
    },
];